name: GH Actions CI
on:
  workflow_dispatch:
    branches:
     - main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Biweekly tests run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 1,15 * *"

concurrency:
  # Specific group naming so CI is only cancelled
  # within same PR or on merge to main
  group: ${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash  -l {0}

jobs:
  main-tests:
    if: "github.repository == 'usnistgov/zenowrapper'"
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macOS-latest, windows-latest]
          mdanalysis-version: ["latest", "develop"]
          python-version: ["3.10", "3.11", "3.12"]
          exclude:
            # Entries here exclude particular combinations of the matrix
            # Edit or remove as particular combinations come into or out of date
            # Below we exclude runs with the latest release and Python 3.12
            - mdanalysis-version: "latest"
              python-version: "3.12"

    steps:
    - uses: actions/checkout@v4

    - name: Build information
      run: |
        uname -a
        df -h
        ulimit -a


    # More info on options: https://github.com/conda-incubator/setup-miniconda
    - name: Install miniconda dependencies
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: devtools/conda-envs/dev_env.yaml
        add-pip-as-python-dependency: true

        miniforge-variant: Miniforge3
        channels: conda-forge, defaults

        activate-environment: zenowrapper-dev
        auto-update-conda: true
        auto-activate-base: false
        show-channel-urls: true


    - name: Install MDAnalysis version
      uses: MDAnalysis/install-mdanalysis@main
      with:
        version: ${{ matrix.mdanalysis-version }}
        install-tests: false
        installer:  mamba
        shell: bash  -l {0}

    - name: Install GCC-11
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
        gcc --version
        g++ --version

    - name: Install GCC-11
      if: runner.os == 'macOS'
      run: |
        brew install gcc@11
        echo "CC=$(brew --prefix gcc@11)/bin/gcc-11" >> $GITHUB_ENV
        echo "CXX=$(brew --prefix gcc@11)/bin/g++-11" >> $GITHUB_ENV

    - name: Install SPRNG
      run: |
        wget http://sprng.org/Version5.0/sprng5.tar.bz2
        tar -xjf sprng5.tar.bz2
        mkdir sprng5-build && cd sprng5-build
        CXXFLAGS=-fPIC ../sprng5/configure --with-fortran=no --with-mpi=no --prefix=$HOME/sprng5-install
        make && make install

    - name: Install ZENO
      run: |
        git clone https://github.com/usnistgov/ZENO.git
        mkdir zeno-build && cd zeno-build
        cmake -DSPRNG_INCLUDE_DIR=$HOME/sprng5-install/include \
              -DSPRNG_LIBRARY=$HOME/sprng5-install/lib/libsprng.a \
              -DCMAKE_INSTALL_PREFIX=$HOME/zeno-install \
              -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
              ../ZENO/cpp
        make && make install
        export ZENOPATH='$HOME/ZENO'

    - name: Install package
      run: |
        python --version
        python -m pip install .  --no-deps

    - name: Python information
      run: |
        which python
        which pip
        pip list

        conda info
        conda list


    - name: Run tests
      run: |
        pytest -n 2 -v --cov=src/zenowrapper --cov-report=xml --cov-report=term-missing --cov-report=html --color=yes src/tests/

    - name: Upload coverage reports to Codecov
      if: github.repository == 'usnistgov/zenowrapper' && github.event_name != 'schedule'
      uses: codecov/codecov-action@v4
      with:
        file: coverage.xml
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
        verbose: True
        # to upload coverage reports, set a secret called CODECOV_TOKEN
        # in the repository settings
        # (Obtain this from the Codecov website after setting up the repository there)
        token: ${{ secrets.CODECOV_TOKEN }}
        # To fail the CI if there's an error, keep this set to true
        # If repository forks need to run CI, you may need to set this to false
        # Forks can't access the CODECOV_TOKEN secret,
        # and a failed upload registers as an error
        fail_ci_if_error: true

    - name: Coverage comment
      if: github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11' && matrix.mdanalysis-version == 'latest'
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ github.token }}
        MINIMUM_GREEN: 90
        MINIMUM_ORANGE: 70

    - name: Store Pull Request comment to be posted
      uses: actions/upload-artifact@v4
      if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
      with:
        name: python-coverage-comment-action
        path: python-coverage-comment-action.txt


  ruff_check:
    if: "github.repository == 'usnistgov/zenowrapper'"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Ruff
      run: |
        which pip
        which python
        pip install ruff

    - name: Run Ruff Linter
      run: |
        ruff check --config pyproject.toml src/zenowrapper

    - name: Run Ruff Formatter Check
      run: |
        ruff format --check --config pyproject.toml src/zenowrapper


  pypi_check:
    if: "github.repository == 'usnistgov/zenowrapper'"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install pipx twine

    - name: Build package
      run: |
        python -m pipx run build --sdist

    - name: Check package build
      run: |
        DISTRIBUTION=$(ls -t1 dist/zenowrapper-*.tar.gz | head -n 1)
        test -n "${DISTRIBUTION}" || { echo "no distribution dist/zenowrapper-*.tar.gz found"; exit 1; }
        echo "twine check $DISTRIBUTION"
        twine check $DISTRIBUTION

  docs:
    name: Build docs on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/Docs4NIST@add_analytics
        with:
          docs-folder: docs/
          conda-environment: devtools/conda-envs/dev_env.yaml
          formats: |-
            epub
            html
